User.create!(name: 'Lucas', email: 'lucas@gmail.com', password: '123456', innkeeper: true)
User.create!(name: 'Gabriel', email: 'gabriel@gmail.com', password: '123456', innkeeper: false)
User.create!(name: 'Oliveira', email: 'oliveira@gmail.com', password: '123456', innkeeper: true)
User.create!(name: 'Aguilar', email: 'aguilar@gmail.com', password: '123456', innkeeper: false)
User.create!(name: 'Valdeir', email: 'valdeir@gmail.com', password: '123456', innkeeper: true)
User.create!(name: 'Ribeiro', email: 'ribeiro@gmail.com', password: '123456', innkeeper: false)